### ISSUE TITLE
Glitchy cursor while changing line

### ISSUE THREAD

**Issue by pcorbineau** [sphamba/smear-cursor.nvim#4] opened 2024-11-24 23:11 UTC
I post also here (from reddit) for issue tracking,

Here is what I see on Windows using plugin on last master `3cacbf0` :

![smearcursor](https://github.com/user-attachments/assets/76c9be74-7cd3-423c-95aa-8271dbafb7f2)

I use default conf using lazy.vim :
```lua
return {
    "sphamba/smear-cursor.nvim",
    opts = {},
}
```

```
wt --version
1.21.3231.0
```

```
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068
```
 
 I retry with a minimal example : 
```lua
 vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
    spec = {
        "stevearc/conform.nvim",
        "nvim-neotest/nvim-nio",
        { "sphamba/smear-cursor.nvim", opts = {} },
    },
})
```
I didnt get the glitch as above but its clearly not smooth 😞

**Comment by pcorbineau** [comment] 2024-11-24 23:19
got the same glitch from windows terminal on cmd.exe and also on wsl2 Ubuntu 24.04

**Comment by pcorbineau** [comment] 2024-11-25 07:31
got exact same behaviour on wezterm (on Windows), I will try later on my linux laptop.

**Comment by sphamba** [comment] 2024-11-25 07:43
I'll try your configuration and let you know. In the meantime, could you check if highlight groups `SmearCursorNormal*` and ``SmearCursorNormalInverted*` (with `*` going from 1 to 16) do exist?

**Comment by pcorbineau** [comment] 2024-11-25 08:11
It looks like I don't have highlight for Smear set up. (I'm not sure if `Telescope highlights` is a good command to check this, I'm a new neovim user)
![image](https://github.com/user-attachments/assets/d0a5f3ef-201b-4862-b794-742d9c93f498)

**Comment by pcorbineau** [comment] 2024-11-25 12:56
Ok super interresting . My config glitch also on my laptop linux.

**Comment by sphamba** [comment] 2024-11-25 12:59
Interesting indeed. I suspect a bad interaction with another plugin. Does the config provided in your original post reproduce the bug?
```lua
require("lazy.minit").repro({
    spec = {
        "stevearc/conform.nvim",
        "nvim-neotest/nvim-nio",
        { "sphamba/smear-cursor.nvim", opts = {} },
    },
})
```

**Comment by pcorbineau** [comment] 2024-11-25 13:04
I don't have the glitch with this minimal config. It looks like my config trigger this.

**Comment by sphamba** [comment] 2024-11-25 17:00
It'd be interesting to know what in your config causes this! It looks like only the definition of highlight groups is compromised. The rest of the plugin seems to work as intended.

**Comment by elliotxx** [comment] 2024-11-26 04:14
I encountered the same problem on the M3 MBP Wezterm. My Neovim plugin configuration is as follows:

https://github.com/elliotxx/lunarvim-config/blob/main/lua/user/plugins.lua

**Comment by sphamba** [comment] 2024-11-28 00:32
> I encountered the same problem on the M3 MBP Wezterm. My Neovim plugin configuration is as follows:
> 
> https://github.com/elliotxx/lunarvim-config/blob/main/lua/user/plugins.lua

I found out that `catppuccin/nvim` is responsible for wiping the highlight groups set by smear_cursor. You may need to make an automatic call to `require("smear_cursor.color").set_hl_groups()`. I'll search how to do it if no one finds it before 🏃🏼‍♂️

**Comment by sphamba** [comment] 2024-11-28 08:38
Should be fixed now. Please re-open if that's not the case

**Closed** 2024-11-28 08:37 UTC
Labels: bug

**Comment by elliotxx** [comment] 2024-11-28 13:31
After I upgrade to the latest version, it's okay

**Comment by pcorbineau** [comment] 2024-11-28 13:50
I confirm it works well now 👍
